# Use root/root as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db_data:/var/lib/mysql

networks:
  default:
    external:
      name: mysql-net